version: "3.7"
services:

    app:
        container_name: app-message-1
        build:
            args:
                user: geowebmaster
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - api-message-1


    nginx:
        container_name: nginx-message-1
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8181:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - api-message-1

    mysql:
        container_name: db-message-1
        image: mysql:5.7.33
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - api-message-1


    # redis:
    #     container_name: redis-message
    #     image: redis:latest
    #     networks:
    #         - api-message

networks:
    api-message-1:
        driver: bridge
